
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.5.45]
ok: [192.168.5.43]

TASK [install updates for fedora] **********************************************
skipping: [192.168.5.45]
fatal: [192.168.5.43]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.5.43 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \u001b[35m\"/home/jesse/.ansible/tmp/ansible-tmp-1744055092.2045882-2843-123215149347440/AnsiballZ_dnf5.py\"\u001b[0m, line \u001b[35m107\u001b[0m, in \u001b[35m<module>\u001b[0m\r\n    \u001b[31m_ansiballz_main\u001b[0m\u001b[1;31m()\u001b[0m\r\n    \u001b[31m~~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^\u001b[0m\r\n  File \u001b[35m\"/home/jesse/.ansible/tmp/ansible-tmp-1744055092.2045882-2843-123215149347440/AnsiballZ_dnf5.py\"\u001b[0m, line \u001b[35m99\u001b[0m, in \u001b[35m_ansiballz_main\u001b[0m\r\n    \u001b[31minvoke_module\u001b[0m\u001b[1;31m(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\u001b[0m\r\n    \u001b[31m~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\r\n  File \u001b[35m\"/home/jesse/.ansible/tmp/ansible-tmp-1744055092.2045882-2843-123215149347440/AnsiballZ_dnf5.py\"\u001b[0m, line \u001b[35m47\u001b[0m, in \u001b[35minvoke_module\u001b[0m\r\n    \u001b[31mrunpy.run_module\u001b[0m\u001b[1;31m(mod_name='ansible.modules.dnf5', init_globals=dict(_module_fqn='ansible.modules.dnf5', _modlib_path=modlib_path),\u001b[0m\r\n    \u001b[31m~~~~~~~~~~~~~~~~\u001b[0m\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\r\n                     \u001b[1;31mrun_name='__main__', alter_sys=True)\u001b[0m\r\n                     \u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\r\n  File \u001b[35m\"<frozen runpy>\"\u001b[0m, line \u001b[35m226\u001b[0m, in \u001b[35mrun_module\u001b[0m\r\n  File \u001b[35m\"<frozen runpy>\"\u001b[0m, line \u001b[35m98\u001b[0m, in \u001b[35m_run_module_code\u001b[0m\r\n  File \u001b[35m\"<frozen runpy>\"\u001b[0m, line \u001b[35m88\u001b[0m, in \u001b[35m_run_code\u001b[0m\r\n  File \u001b[35m\"/tmp/ansible_ansible.legacy.dnf5_payload_dtjq8t82/ansible_ansible.legacy.dnf5_payload.zip/ansible/modules/dnf5.py\"\u001b[0m, line \u001b[35m708\u001b[0m, in \u001b[35m<module>\u001b[0m\r\n  File \u001b[35m\"/tmp/ansible_ansible.legacy.dnf5_payload_dtjq8t82/ansible_ansible.legacy.dnf5_payload.zip/ansible/modules/dnf5.py\"\u001b[0m, line \u001b[35m704\u001b[0m, in \u001b[35mmain\u001b[0m\r\n  File \u001b[35m\"/tmp/ansible_ansible.legacy.dnf5_payload_dtjq8t82/ansible_ansible.legacy.dnf5_payload.zip/ansible/modules/dnf5.py\"\u001b[0m, line \u001b[35m487\u001b[0m, in \u001b[35mrun\u001b[0m\r\n\u001b[1;35mAttributeError\u001b[0m: \u001b[35m'Base' object has no attribute 'load_config_from_file'\u001b[0m\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
192.168.5.43               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
192.168.5.45               : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

